### ISSUE TITLE
Global encoder

### ISSUE THREAD

**Issue by Nakrasi97** [CIAM-Group/NCO_code#21]
Hi. I can't find the implementation of the global encoder within the source code for MORAM.
Could you point me to it if I am missing it?

**Comment by ShunyuYao6** [comment]
Thanks for your question. The global encoder in our code implementation is referred to as **mix_gat**. It is worth noting that while the name may appear mismatched, the implementation itself is accurate.

**Comment by Nakrasi97** [comment]
Thanks for your response. That was very helpful.
