### ISSUE TITLE
Issue about the TSPLib and CVPRLib datasets

### ISSUE THREAD

**Issue by gaocrr** [CIAM-Group/NCO_code#5]
Thanks for your excellent research! Could you provide the preprocessed TSPLib and CVRPLib datasets (in your .txt format)? It may be tedious for users to convert the original file format to the .txt format that your code could process.

**Comment by L-fu-des22** [comment]
Oh, thank you for your interest in our work! And sorry to reply so late, I just saw this issue. I have uploaded the TSPlib/CVRPlib .txt file tested in our paper to the path [`LEHD/TSP/data`](https://github.com/CIAM-Group/NCO_code/tree/main/single_objective/LEHD/TSP/data) and  [`LEHD/CVRP/data`](https://github.com/CIAM-Group/NCO_code/tree/main/single_objective/LEHD/CVRP/data). Also the corresponding test Python file is uploaded, such as [test_inTSPlib.py](https://github.com/CIAM-Group/NCO_code/blob/main/single_objective/LEHD/TSP/test_inTSPlib.py) and [test_inCVRPlib.py](https://github.com/CIAM-Group/NCO_code/blob/main/single_objective/LEHD/CVRP/test_inCVRPlib.py). Hope it will solve this issue.

**Comment by gaocrr** [comment]
Thanks for your response! My issue is solved.
